### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by nader-aeinehchi** [danluu/akka-concurrency-wyatt#2]
Hi.

I use SCALA-IDE 3.0.1 final with Akka 2.2.1 and Scala 2.10.2.

When I import the source into Eclipse, I get several compilation errors.  Examples:
1. Plane.scala: 
   val maleBathroomCounter = Agent(GenderAndTime(Male, 0.seconds, 0))(context.system)
   Here the last argument is not recognized (context.system).  When removed, the code compiles.
2. Plane.scala
   val male = maleBathroomCounter.await
   error message: "value await is not a member of akka.agent.Agent[zzz.akka.avionics.GenderAndTime]

It would be nice which versions of Scala and Akka the code fully compiles.

Thanks

**Comment by danluu** [comment]
From the build.sbt, it looks like I was using scala 2.10.0 and akka 2.1.1. If you're familiar with sbt, you can use it to produce a project that will correctly import to eclipse, via sbteclipse. The plugins.sbt already includes that, so I believe it should work if you run sbt from that directory and the type 'eclipse'

Also, I'd be happy to take [a pull request](https://help.github.com/articles/using-pull-requests) that updates things to work for the latest version.
