### ISSUE TITLE
Min/Mac

### ISSUE THREAD

**Issue by ayubmalik** [danluu/akka-concurrency-wyatt#7]
In Altimeter.scala should the value on min/max not be the other way round?

rateOfClimb = amount.min(1.0f).max(-1.0f) \* maxRateOfClimb

**Comment by danluu** [comment]
I haven't looked at this code for about a year, but I don't think so.

Consider something above [-1, 1], like 5. `min(1, 5) = 1`, so it gets chopped to `1`. Same for something below `-1` that's affected by the `max`.

Anything between [-1, 1] won't be affected. Like I said, I haven't looked at this for ages, but I believe the intent is to keep the range between [-1, 1] and that this does so.

**Comment by ayubmalik** [comment]
Oops, you are correct. I misinterpreted how the min/max functions work(!)
